version: "3.9"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    command: sh -c "rm -f /jet/server/tmp/pids/server.pid && cd /jet/server && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/jet
      - ./server:/jet/server
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - db

  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    volumes:
      - .:/jet
      - ./client:/jet/client
      - node_modules:/jet/client/node_modules
    command: sh -c "yarn && yarn dev"
    ports:
      - 8000:3000

volumes:
  postgres-data:
  node_modules:
